# List of supported mod loaders
loaders = [ "Fabric", "Forge" ]

# The version the profile supports using semver.
version = ">=1.21.1"

# List of mods
[mods]
# Specify the mod source
sodium = "modrinth:sodium"
# Specify multiple sources for the mod
iris-shaders = [ "modrinth:YL57xq9U", "curseforge:455508" ]

# Specify even more information about a mod
[mods.create]
# The 'create' mod supports forge and fabric
mod_loader = [ "Fabric", "Forge" ]
src = [
    # Add a fabric only source
    { mod_loader = [ "Fabric" ], src = "curseforge:624165" },
    # Add a forge only source
    { mod_loader = [ "Forge" ], src = "curseforge:328085" }
]

# List of resource packs
[resourcepacks]
# Use a shorthand, `cf` instead of `curseforge`
dynamic-surroundings = "cf:993859"

# List of shaders
[shaders]
# Use slug instead of id
complementary = [ "mr:complementary-unbound", "cf:385587" ]

# List of modpacks, each mod in the packs will be included
# TODO: Modpacks are currently not supported
[modpacks]
fabulously-optimized = [ "mr:fabulously-optimized", "cf:396246" ]