name: Bug Report
description: Report behaviour that should not occur
type: Bug
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How do you reproduce this bug? You can also describe how you encountered the bug if you are unsure.
      placeholder: |
        For example:
        1. Run `ferium ...`
        2. ... doesn't properly change
        3. Run command again
        4. ... changes properly
        ...

  - type: dropdown
    attributes:
      label: Operating System
      description: The operating system you encountered the bug on
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - other (Specify in Additional Information)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Installation Method
      description: How did you install ferium?
      options:
        - AUR (pacman)
        - Homebrew
        - winget
        - Scoop
        - Pacstall
        - Nixpkgs
        - LoaTcHi's overlay (Gentoo Portage)
        - XBPS
        - crates.io (`cargo install`)
        - GitHub Releases (manually installed)
        - Locally compiled
        - GitHub Actions
    validations:
      required: true

  - type: input
    attributes:
      label: Ferium version
      description: What is the output of `ferium --version`?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information you would like to provide. You can even drop images or videos here.
