# An overrides directory,
# all files and folders in the directory will be placed in `.minecraft`
overrides = "./overrides"

# Modify the `options.txt` file from a profile,
[options]
# Make the mojang studios background dark.
darkMojangStudiosBackground = true

# Set the keybinds, you can use key codes or key ids
[options.keybinds]
# Set the swapOffhand button to "Z"
key_key.swapOffhand = 44
# Set the togglePerspective button to "F"
key_key.togglePerspective = "key.keyboard.f"

# Specify more mods,
# these will get imported into the profile
[mods]
blahaj-of-undying = "mr:aJb4vlkM"
sound-physics-remastered = "mr:qyVF9oeo"
